Updated setup.py enforcing utf-8 read
I have found that python3.x installation via pip is failing due to python3 "UnicodeDecodeError" (see below).

UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 4335: ordinal not in range(128)

This change simply enforces utf-8 read in of the readme.rst file and allows for the package to install correctly.